#!/bin/bash
#Versao 0.2
###_xXkrill3Xx_
      ##Ferramentas##
apt-get install git && apt-get install wget
apt-get install python && apt-get install python2
apt-get install php && apt-get install curl
apt-get install nano && apt-get install clang
apt-get install perl && apt-get install vim
apt-get install coreutils && apt-get install ruby
apt-get install toilet && apt-get install fish
apt-get install ifconfig && apt-get install openssh
apt-get install w3m && apt-get install nmap
apt-get install termux-api && apt-get install figlet
apt-get install cowsay && cowsay "usar o cowsay e fácil (cowsay "exemplo")"
