#!/bin/bash
#_xXkrill3Xx_
#1.0
echo "PRINCIPAIS FERRAMENTAS QUE UM INICIANTE PRECISA :^" 
echo "confirme a instalação com ( Y ) e não confirme com ( N )"
echo "quando for usar termux sempre usar (pkg upgrade && pkg update)"
pkg upgrade && pkg update
echo "leia os comandos e treine"
echo "para instalação de uma ferramenta sempre usar (git clone www.github.com/exemplo)"
echo "para remover (rm exemplo) caso não saia use (rm -rf exemplo)"
echo "mover repositório (mv exemplo $HOME/storage/downloads)"
echo "se estiver perdido entre as pastas use (pwd), se quiser voltar a pasta anterior use (cd ..), volta para $HOME(cd), abrir pastas (cd exemplo)"
echo "sempre que quiser ver repositórios dentro de uma pasta basta da o comando (ls) e você verá repositórios etc"
echo "quando abrir uma pasta use (chmod +x *) para dar permissão a todos repositórios ou (chmod +x exemplo) para dar permissão a um único repositório"
echo "agora vc dará permissão ao termux para ter acesso aos seus arquivos (termux-setup-storage)"
termux-setup-storage
echo "para instalação de alguma ferramenta (pkg install exemplo) ou (apt install exemplo)"
pkg install bash
echo "execute para instala ferramentas-> (bash bilin)" && echo "Feito por _xXKrill3Xx_" && sleep 15s;
